name: Write Good

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  write_good:
    name: Write Good
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run local write-good action
        uses: ./.github/actions/write-good
